
  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: Roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app


  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: download {{ component }} app code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip 
      dest: /tmp/{{ component }}.zip


  - name: extract {{ component }} application
    ansible.builtin.unarchive:
      src: /tmp/{{ component }}.zip
      dest: /app
      remote_src: yes
